Js issues
lalitkumarthakur/thapatechnicalJavaScript_course pull request #90
Opened 2023-11-27 16:32 UTC by VishalD51

Print 3rd array.

2023-11-28 04:43 UTC, lalitkumarthakur requested changes
Hi,
Thanks for requesting the PR as instructed. But there is a problem you did, and you have to face inconvenience for that, and I am sorry for that in advanced.

You have changes double inverted commas to single. And I don't like that fact. Please revert the changes and use "" commas through the code.

I come from a Java Background, I don't want to use Single Inverted commas. I understand that different devs has different preferences, but please use as instructed because I have used double invited commas thought the project.

Thanks.

2023-11-28 05:14 UTC, lalitkumarthakur commented
Please sync the latest changes at the time of comiting to avoid any conflicts @VishalD51

2023-11-29 04:57 UTC, VishalD51 commented
> Hi @VishalD51 , Thanks for requesting the PR as instructed. But there is a problem you did, and you have to face inconvenience for that, and I am sorry for that in advanced.
> 
> You have changes double inverted commas to single. And I don't like that fact. Please revert the changes and use "" commas through out the code.
> 
> I come from a Java Background, I don't want to use Single Inverted commas. I understand that different devs has different preferences, but please use as instructed because I have used double invited commas thought out the project.
> 
> Thanks.

@lalitkumarthakur Sorry for inconsistency, I will improve it and raise PR.

2023-12-02 12:57 UTC, VishalD51 commented
@lalitkumarthakur , can you please check this PR?

2023-12-02 16:24 UTC, lalitkumarthakur commented
@VishalD51 Hi, I am busy and running out of deadlines, so I could not review as Of now. Please be patient. December 1st and 2nd week will be hectic for me because I have to wrap up JavaScript and Finish 80% of React.js, and we know it's near to impossible to do so. 
Till then, 
You can see the code, go through the chapters, 
Flag any issues and solve current issues present where help is required on urgent basis.

Thanks,
Lalit.

2023-12-04 07:03 UTC, namokumar requested changes
Hi @VishalD51, I have reviewed ypir PR and output is not as expected! 

Let me demonstrated the output here - 

the array is 

usersInfo = [
        [
          "Sneha",
          "Shreya",
          "Arup",
          "Priyanka",
          "Vinit",
          "Vanshika",
          "Olyvia",
          ["chatterjee", "bogopaddhayai", "grop", "singh", "verma", "Cornelo"],
        ],
        [true, false, true, true, false, true, false, true],
        [21, 29, 26, 23, 25, 19, 24],
];

in which  
[
          "Sneha",
          "Shreya",
          "Arup",
          "Priyanka",
          "Vinit",
          "Vanshika",
          "Olyvia", ["chatterjee", "bogopaddhayai", "grop", "singh", "verma", "Cornelo"],
        ], is 1st external array and Inside this array 
        ["chatterjee", "bogopaddhayai", "grop", "singh", "verma", "Cornelo"]
        is another array which makes it a Array Inside a Array inside a Array (3times).
        
Now, there are 2 separate External arrays-
[true, false, true, true, false, true, false, true],
        [21, 29, 26, 23, 25, 19, 24],
        
So, the printing order should be-

1st External Array - Sneha, Shreya, Arup, Priyanka, Vinit, Vanshika, Olyvia
2nd Array inside 1st External Array - chatterjee, bogopaddhayai, grop, singh, verma, Cornelo
2nd External Array - true, false, true, true, false, true, false, true
3rd External Array - 21, 29, 26, 23, 25, 19, 24

This is how each and all elements should be printed.

Please explain the code line by Line via comments, as this is a difficult question.


Sorry for unclear instructions/misunderstanding and incontinence
![output not as expected 2](https://github.com/lalitkumarthakur/thapatechnicalJavaScript_course/assets/45649399/fe3a0c4b-a75a-4f16-bcb5-13cc47be8e97)
![out not as expected1](https://github.com/lalitkumarthakur/thapatechnicalJavaScript_course/assets/45649399/d36406e3-dc70-44a5-bca8-6db6e1e806cb)
 caused.
Thanks.

2023-12-22 15:23 UTC, lalitkumarthakur commented
Hi @VishalD51 , I do not see any activity from your side regarding this issue. Please clear me that "are you willing to contribute further? Or leave it from here itself?"

2023-12-23 07:03 UTC, VishalD51 commented
@lalitkumarthakur, Yes  I want to contribute further and also try solve other issues soon. I am busy with other priority projects. Sorry for that.

2024-02-09 06:52 UTC, lalitkumarthakur commented
Hi @VishalD51 , There is no activity from your side. Please be a responsible contributor and complete the task which you have taken. Once the task is completed, then you are free to discontinue or stop contributing to this project.

2024-08-13 08:11 UTC, lalitkumarthakur commented
Hi @VishalD51, there is no activity from your side from a long time. Do you want to contribute to this project and solve the issue?

2025-08-04 10:57 UTC, namokumar commented
Added @VishalD51 changes in prod.Will fix issues later

2025-08-04 10:57 UTC, closed without merging